# Generated by Django 4.1.5 on 2023-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='chapters',
            field=models.IntegerField(default=0),
        ),
    ]
