# Generated by Django 4.1.5 on 2023-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novelmodel_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='info',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
