# Generated by Django 4.1.5 on 2023-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_remove_novelmodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='info',
            field=models.JSONField(),
        ),
    ]
