# Generated by Django 4.1.5 on 2023-03-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0014_alter_novelmodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
