# Generated by Django 4.1.5 on 2023-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0016_alter_novelmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='cover',
            field=models.ImageField(default=None, max_length=10000, upload_to=''),
        ),
    ]
