# Generated by Django 4.1.5 on 2023-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0023_alter_novelmodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='chapters',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='cover',
            field=models.ImageField(db_index=True, default=None, max_length=10000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='views',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
