# Generated by Django 4.1.5 on 2023-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0024_alter_novelmodel_chapters_alter_novelmodel_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelmodel',
            name='cover',
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='cover_url',
            field=models.CharField(db_index=True, default='', max_length=10000),
        ),
    ]
