# Generated by Django 4.1.5 on 2023-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0026_novelmodel_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='cover_url',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='last_edited',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
