# Generated by Django 4.1.5 on 2023-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0027_alter_novelmodel_chapters_alter_novelmodel_cover_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='views',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
